
rust:
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_8eea97380c73_key -iv $encrypted_8eea97380c73_iv
  -in secure.json.enc -out ~/secure.json -d
  language: rust
deploy:
  provider: gae
  keyfile: ~/secure.json
  project: vrdata-dev
  skip_cleanup: true
